name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Select Terraform action'
        required: true
        default: 'apply'
        options:
          - 'apply'

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.3

      - name: No-op
        run: echo "No-op"

      - name: Terraform Init & Apply
        run: |
          terraform init -var="instance_type=t2.micro"
          terraform apply -auto-approve -var="instance_type=t2.micro"
